# Generated by Django 5.2.7 on 2025-10-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_uploadedfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game',
            new_name='game_name',
        ),
    ]
