# Generated by Django 5.2.7 on 2025-10-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_game_game_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchild',
            name='section',
            field=models.CharField(blank=True, null=True),
        ),
    ]
