# Generated by Django 5.2.7 on 2025-10-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_userchild_class_sched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchild',
            name='class_sched',
            field=models.CharField(blank=True, choices=[('morning', '8:00 AM to 11:00 AM'), ('noon', '11:00 AM to 1:00 PM')], max_length=30, null=True),
        ),
    ]
