# Generated by Django 5.2.7 on 2025-10-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_userchild_class_sched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchild',
            name='class_sched',
            field=models.CharField(blank=True, choices=[('8:00 AM to 11:00 AM', '8:00 AM to 11:00 AM'), ('11:00 AM to 1:00 PM', '11:00 AM to 1:00 PM')], max_length=30, null=True),
        ),
    ]
