# Generated by Django 5.2.7 on 2025-10-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_userchild_class_sched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchild',
            name='section',
            field=models.CharField(default='Section A', editable=False, max_length=30),
        ),
    ]
