# Generated by Django 5.2.7 on 2025-10-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_userchild_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchild',
            name='section',
            field=models.CharField(blank=True, default='Kinder2: PIAGET', editable=False, max_length=30, null=True),
        ),
    ]
