# Generated by Django 5.2.7 on 2025-11-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_userchild_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='role',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Parent', 'Parent'), ('Admin', 'Admin')]),
        ),
    ]
