# Generated by Django 5.2.7 on 2025-11-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_roles_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='role',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Parent', 'Parent'), ('Admin', 'Admin')], max_length=20, unique=True),
        ),
    ]
