# Generated by Django 5.2.7 on 2025-11-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_create_default_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='difficulty',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_name',
            field=models.CharField(choices=[('Lesson1 Activity1', 'Lesson1 Activity1'), ('Lesson1 Activity2', 'Lesson1 Activity2'), ('Lesson2 Activity1', 'Lesson2 Activity1'), ('Lesson2 Activity2', 'Lesson2 Activity2'), ('Lesson3 Activity1', 'Lesson3 Activity1'), ('Lesson3 Activity2', 'Lesson3 Activity2'), ('Lesson4 Activity1', 'Lesson4 Activity1'), ('Lesson4 Activity2', 'Lesson4 Activity2'), ('Lesson5 Activity1', 'Lesson5 Activity1'), ('Lesson5 Activity2', 'Lesson5 Activity2')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='one_star_time',
            field=models.IntegerField(default=45, help_text='Max time for 1 star'),
        ),
        migrations.AlterField(
            model_name='game',
            name='three_star_time',
            field=models.IntegerField(default=20, help_text='Max time for 3 stars'),
        ),
        migrations.AlterField(
            model_name='game',
            name='two_star_time',
            field=models.IntegerField(default=30, help_text='Max time for 2 stars'),
        ),
    ]
