# Generated by Django 5.2.7 on 2025-11-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_game_difficulty_alter_game_game_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='level',
        ),
    ]
