# Generated by Django 5.2.7 on 2025-11-03 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_game_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecompletion',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_records', to='api.userchild'),
        ),
        migrations.AlterField(
            model_name='timecompletion',
            name='star',
            field=models.IntegerField(choices=[(0, 'No Stars'), (1, '1 Star'), (2, '2 Stars'), (3, '3 Stars')], default=0),
        ),
    ]
